name: terraform apply on staging

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 0.14.8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terrafor Apply
        id: apply
        run: terraform apply -auto-approve
        continue-on-error: true
        working-directory: ./environments/staging

      - name: output
        run: |
          echo ${{ steps.apply.outputs.stdout }}
